import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import React from "react";
import CreateProduct from "~/components/Products/ProductWizard";
import Products from "~/components/Products";
import Test from "~/components/Test";

import { api } from "~/utils/api";
import StoreLayout from "~/components/Layouts/store-layout";


const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
 

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StoreLayout>
       <Test/>
       <Products/>
      </StoreLayout>
    </>
  );
};

export default Home;